site_name: Сайтикс

nav:
  - Главная: index.md
  - Обо мне: about.md
  - Лабораторные: labs.md
  - Отчеты:
    - laba1.md
    - temple.md

theme: 
  name: dracula
  logo: assets/kotik.jpg
  favicon: assets/favicon.jpg
